package common;

import rs2d.spinlab.sequenceGenerator.GeneratorSequenceParamEnum;

public enum CommonSP implements GeneratorSequenceParamEnum{
    Tx_att,
    Tx_att_offset,
    Tx_att_offset_180,
    Rx_gain,
    Rx_freq_offset,
    Rx_phase,
    Intermediate_frequency,
    Spectral_width,
    Tx_frequency,
    Tx_nucleus,
    Time_tx,
    Time_tx_180,
    Time_rx,
    Time_min_instruction,
    Tx_amp,
    Tx_amp_180,
    Tx_phase,
    Tx_phase_180,
    Tx_shape,
    Tx_shape_180,
    Tx_shape_phase,
    Tx_shape_phase_180,
    Tx_freq_offset,
    Tx_freq_offset_180,
    LO_att,
    Phase_reset,
    Grad_shape_rise_up,
    Grad_shape_rise_down,
    Gradient_axe_phase,
    Gradient_axe_read,
    Gradient_axe_slice,
    Grad_amp_read_prep,
    Grad_amp_phase_2D_prep,
    Grad_amp_phase_2D_comp,
    Grad_amp_phase_3D_prep,
    Grad_amp_phase_3D_comp,
    Grad_amp_slice,
    Time_grad_ramp,
    Time_grad_phase_top,
    Pre_scan,
    Nb_1d,
    Nb_2d,
    Nb_3d,
    Nb_4d,
    Nb_point,
    Nb_echo,
    Nb_interleaved_slice,
    ;
}
